<a href="https://colab.research.google.com/github/george-studenko/100_Days_of_ML_Code/blob/master/code/Celsius_to_Fahrenheit_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torch import optim

𝑓=𝑐×1.8+32

In [0]:
celsius    = np.array([[-40], [-10],  [0],  [8], [15], [22],  [38]],  dtype=float)
fahrenheit = np.array([[-40],  [14], [32], [46.4], [59], [71.6], [100.4]],  dtype=float)

test_set = np.array([[71],  [94], [117]],  dtype=float)
test_set_result_should_be = np.array([[159.8],  [201.2], [242.6]],  dtype=float)


In [0]:
celsius = Variable(torch.from_numpy(celsius))
fahrenheit = Variable(torch.from_numpy(fahrenheit))

test_set = Variable(torch.from_numpy(test_set))
test_set_result_should_be = Variable(torch.from_numpy(test_set_result_should_be))

In [131]:
celsius[0]

tensor([-40.], dtype=torch.float64)

In [0]:
linear_model = nn.Linear(1,1)

In [146]:
linear_model

Linear(in_features=1, out_features=1, bias=True)

In [147]:
linear_model.weight

Parameter containing:
tensor([[-0.4284]], requires_grad=True)

In [148]:
linear_model.bias

Parameter containing:
tensor([0.1566], requires_grad=True)

In [0]:
linear_model.double()
y = linear_model(celsius[0])

In [150]:
y

tensor([17.2945], dtype=torch.float64, grad_fn=<AddBackward0>)

In [0]:
criterion = nn.MSELoss()
sgd_optimizer = optim.SGD(linear_model.parameters(),lr = 0.001)

In [168]:
epochs = 600
print_every = 50
steps = 0

for epoch in range(epochs):
    running_loss = 0
    
    linear_model.train()
    
    # train
    for index in range(len(celsius)):
        steps += 1
        
        # Set gradients to zero
        sgd_optimizer.zero_grad()
        
        y_hat = linear_model.forward(celsius[index])
        loss = criterion(y_hat,fahrenheit[index])
        loss.backward()
        sgd_optimizer.step()
        
        running_loss += loss.item()
        
        if steps % print_every == 0:
            linear_model.eval()
            
            print("Epoch: {}/{}... ".format(epoch+1, epochs),
                  "Loss: {:.3f}".format(running_loss/print_every))
            
            running_loss = 0
            linear_model.train()

Epoch: 8/600...  Loss: 0.000
Epoch: 15/600...  Loss: 0.000
Epoch: 22/600...  Loss: 0.000
Epoch: 29/600...  Loss: 0.000
Epoch: 36/600...  Loss: 0.000
Epoch: 43/600...  Loss: 0.000
Epoch: 50/600...  Loss: 0.000
Epoch: 58/600...  Loss: 0.000
Epoch: 65/600...  Loss: 0.000
Epoch: 72/600...  Loss: 0.000
Epoch: 79/600...  Loss: 0.000
Epoch: 86/600...  Loss: 0.000
Epoch: 93/600...  Loss: 0.000
Epoch: 100/600...  Loss: 0.000
Epoch: 108/600...  Loss: 0.000
Epoch: 115/600...  Loss: 0.000
Epoch: 122/600...  Loss: 0.000
Epoch: 129/600...  Loss: 0.000
Epoch: 136/600...  Loss: 0.000
Epoch: 143/600...  Loss: 0.000
Epoch: 150/600...  Loss: 0.000
Epoch: 158/600...  Loss: 0.000
Epoch: 165/600...  Loss: 0.000
Epoch: 172/600...  Loss: 0.000
Epoch: 179/600...  Loss: 0.000
Epoch: 186/600...  Loss: 0.000
Epoch: 193/600...  Loss: 0.000
Epoch: 200/600...  Loss: 0.000
Epoch: 208/600...  Loss: 0.000
Epoch: 215/600...  Loss: 0.000
Epoch: 222/600...  Loss: 0.000
Epoch: 229/600...  Loss: 0.000
Epoch: 236/600...  Los

In [169]:
linear_model.weight.item()

1.7999996045985154

In [170]:
linear_model.bias.item()

31.99994722691993

In [0]:
def run_tests():
  for index in range(len(test_set)):
    prediction = linear_model(test_set[index])
    label = test_set_result_should_be[index]
    print(f'Prediction:{prediction.item()} Label: {label.item()}')


In [181]:
run_tests()

Prediction:159.79991915341452 Label: 159.8
Prediction:201.19991005918035 Label: 201.2
Prediction:242.59990096494624 Label: 242.6


In [0]:
def run_tests():
  for index in range(len(test_set)):
    prediction = linear_model(test_set[index])
    prediction = round(prediction.item(),2)
    label = test_set_result_should_be[index]
    print(f'Rounded Prediction:{prediction} Label: {label.item()}')

In [183]:
run_tests()

Prediction:159.8 Label: 159.8
Prediction:201.2 Label: 201.2
Prediction:242.6 Label: 242.6
